[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78872 - LOGS_CAPTURED - Started capturing logs in process (pid: 78872).
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78872 - data_quality_checks - STEP_START - Started execution of step "data_quality_checks".
/Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/datastack_orchestration/assets.py:155: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn).iloc[0, 0]
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78872 - data_quality_checks - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - data_quality_checks - Writing file at: /Users/op/Desktop/data-stack-exercise/data-stack-exercise/modern-data-stack/dagster_project/datastack_orchestration/.tmp_dagster_home_jafx14dh/storage/data_quality_checks using PickledObjectFilesystemIOManager...
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78872 - data_quality_checks - ASSET_MATERIALIZATION - Materialized value data_quality_checks.
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78872 - data_quality_checks - HANDLED_OUTPUT - Handled output "result" using IO manager "io_manager"
[32m2025-08-20 10:34:47 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4f7a2e6f-c0b8-4cdf-b713-b41909d9c98d - 78872 - data_quality_checks - STEP_SUCCESS - Finished execution of step "data_quality_checks" in 158ms.
